// Sumit_Goyal_Day2_HandsOn_QuadB/src/rustproject_one_frontend/src/App.jsx
import { useState } from 'react';
import { rustproject_one_backend } from 'declarations/rustproject_one_backend';

function App() {
  const [greeting, setGreeting] = useState('');

  function handleSubmit(event) {
    event.preventDefault();
    const name = event.target.elements.name.value;
    rustproject_one_backend.greet(name).then((greeting) => {
      setGreeting(greeting);
    });
    return false;
  }

  return (
    <main>
      <img src="/logo2.svg" alt="DFINITY logo" />
      <br />
      <br />
      <form action="#" onSubmit={handleSubmit}>
        <label htmlFor="name">Enter your name: &nbsp;</label>
        <input id="name" alt="Name" type="text" />
        <button type="submit">Click Me!</button>
      </form>
      <section id="greeting">{greeting}</section>
    </main>
  );
}

export default App;

// Sumit_Goyal_Day3_HandsOn_QuadB/src/viewJsFrontendDetails/App.vue
<script setup>
import { ref } from 'vue';
import { project_backend } from '../../declarations/project_backend/index.js';
let greeting = ref('');

async function handleSubmit(e) {
  e.preventDefault();
  event.preventDefault();
  
  try {
    const name = event.target.elements.name.value;
    const backendActor = await project_backend();
    console.log("backendActor:", backendActor);

    const response = await backendActor?.greet(name);
    console.log("greeting:", response);

    greeting.value = response;
  } catch (error) {
    console.error("Error in handleSubmit:", error);
  }
}
</script>

<template>
  <main>
    <img src="/logo2.svg" alt="ICP-CLI logo" />
    <br />
    <br />
    <form action="#" @submit="handleSubmit">
      <label for="name">Enter your name: &nbsp;</label>
      <input id="name" alt="Name" type="text" />
      <button type="submit">Click Me!</button>
    </form>
    <section id="greeting">{{ greeting }}</section>
  </main>
</template>
